version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - '8080:8000'
    volumes:
      - ${LOCAL_PATH}:${STORAGE_PATH}
    environment:
      - HOST_URL=${HOST_URL}
      - CLIENT_PORT=${CLIENT_PORT}
  client:
    build:
      context: ./client
      args:
        - VITE_HOST_URL=${HOST_URL}
        - VITE_SERVER_PORT=${SERVER_PORT}
        - VITE_STORAGE_PATH=${STORAGE_PATH}
    ports:
      - '8081:3000'
    